import {
  Body,
  Controller,
  HttpCode,
  HttpStatus,
  Post,
  InternalServerErrorException,
  Logger,
} from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags } from '@nestjs/swagger';
import { ClaudeAgentService } from './claude-agent.service';
import {
  SmartNotificationRequest,
  SmartNotificationResponse,
} from '../notifications/dto/product-event.dto';

/**
 * REST controller for the Claude AI notification agent (Section 6B).
 *
 * This endpoint is consumed by:
 *   1. Internal services that need AI-generated notification copy before sending.
 *   2. The admin dashboard for previewing what notification a given event would produce.
 *   3. A/B testing pipelines comparing AI-generated vs template-based messages.
 *
 * It is deliberately separate from the Pub/Sub subscription path: the subscriber
 * processes events at high throughput and does not need AI per message (cost and
 * latency would be prohibitive). AI generation is reserved for cases where
 * notification quality matters more than throughput.
 */
@ApiTags('agent')
@Controller('agent')
export class AgentController {
  private readonly logger = new Logger(AgentController.name);

  constructor(private readonly claudeAgent: ClaudeAgentService) {}

  /**
   * Generate an AI-powered notification for a product event.
   *
   * Returns a structured notification with subject, body, and recommended
   * delivery channel — all generated by Claude based on the event context.
   */
  @Post('smart-notification')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Generate a Claude-powered smart notification',
    description:
      'Uses Claude claude-haiku-4-5 to generate a personalised notification subject, body, and ' +
      'recommended channel (email/push/sms) for a product domain event. ' +
      'Requires ANTHROPIC_API_KEY to be set.',
  })
  @ApiResponse({
    status: 200,
    description: 'AI-generated notification content',
    type: SmartNotificationResponse,
  })
  @ApiResponse({ status: 400, description: 'Invalid request body' })
  @ApiResponse({ status: 500, description: 'Claude API error or missing API key' })
  async generateSmartNotification(
    @Body() request: SmartNotificationRequest,
  ): Promise<SmartNotificationResponse> {
    this.logger.log(
      `Smart notification requested for event ${request.event.eventType} / product ${request.event.entityId}`,
    );

    try {
      return await this.claudeAgent.generateNotification(
        request.event,
        request.audienceContext,
      );
    } catch (error) {
      this.logger.error('Claude agent failed to generate notification', (error as Error).stack);
      // Do not leak the internal error message to the client — it may contain
      // API keys, internal model details, or stack traces.
      throw new InternalServerErrorException(
        'Failed to generate notification content. Check ANTHROPIC_API_KEY and service logs.',
      );
    }
  }
}
